### ISSUE TITLE
tf-idf buggy

### ISSUE THREAD

**Issue by ssagaert** [johnmyleswhite/TextAnalysis.jl#25]
ERROR: `/` has no method matching /(::Int64, ::Array{Int64,2})
 in tf_idf at /home/steven/.julia/v0.3/TextAnalysis/src/tf_idf.jl:52
 in tf_idf at /home/steven/.julia/v0.3/TextAnalysis/src/tf_idf.jl:74

here is a correct version:

function tf_idf{T <: Real}(dtm::Matrix{T})
    n, p = size(dtm)

    # TF tells us what proportion of a document is defined by a term
    tf = Array(Float64, n, p)
    # IDF tells us how rare a term is in the corpus
    idf=Array(Float64,p)
    for i in 1:n
        words_in_document = 0
        for j in 1:p
            words_in_document += dtm[i, j]
            idf[j]=log(n/sum(vec(dtm[:,j])))
        end
        tf[i, :] = dtm[i, :] / words_in_document
    end

    # TF-IDF is the product of TF and IDF
    # We store it in the TF matrix to save space
    for i in 1:n
        for j in 1:p
           tf[i, j] = tf[i, j] * idf[j]
        end
    end

    return tf
end

# TODO: Rewrite this definition to return a sparse matrix
function tf_idf{T <: Real}(dtm::SparseMatrixCSC{T})
    n, p = size(dtm)

    # TF tells us what proportion of a document is defined by a term
    tf = Array(Float64, n, p)
    # IDF tells us how rare a term is in the corpus
    idf=Array(Float64,p)
    for i in 1:n
        words_in_document = 0
        for j in 1:p
            words_in_document += dtm[i, j]
            idf[j]=log(n/sum(vec(dtm[:,j])))
        end
        tf[i, :] = dtm[i, :] / words_in_document
    end

    # TF-IDF is the product of TF and IDF
    # We store it in the TF matrix to save space
    for i in 1:n
       for j in 1:p
          tf[i, j] = tf[i, j] * idf[j]
        end
    end

    return tf
end

function tf_idf!{T <: Real}(dtm::Matrix{T})
    error("not yet implemented")
end

function tf_idf!{T <: Real}(dtm::SparseMatrixCSC{T})
    error("not yet implemented")
end

function tf_idf(dtm::DocumentTermMatrix)
    tf_idf(dtm.dtm)
end

function tf_idf!(dtm::DocumentTermMatrix)
    tf_idf!(dtm.dtm)
end

**Comment by aviks** [comment]
I believe this has been fixed by https://github.com/johnmyleswhite/TextAnalysis.jl/commit/d40a74e48fc1822d22b128af0bd76e0c27ec10c1

While the fix is before the date of this issue, this hadn't been tagged in a new version.

**Comment by aviks** [comment]
This is fixed in `v0.0.2`
