### ISSUE TITLE
MethodError(getindex Error with corpus

### ISSUE THREAD

**Issue by LeonardoReyes** [johnmyleswhite/TextAnalysis.jl#29]
Hello,

I am fairly new but very enthusiastic about text mining in Julia. I have managed to some of the basics metrics in the introductory documentation, however I am running with lots of error messages now that I am trying to work with corpuses. Every time that I tried to standardize or run other commands I get this message:

    MethodError(getindex,(A Corpus,1))

Probably is something straightforward but documentation is scarce. Any hint would be really appreciated.

**Comment by johnmyleswhite** [comment]
Unfortunately, this package is best thought of as "temporarily deprecated" until I have more time to work on it. Until then, the best way to solve problems is to slog through reading the source code.

**Comment by aviks** [comment]
@LeonardoReyes its been a while, but can you tell us if there a stacktrace? And what exact methods (and inputs) you were trying to run?

**Comment by aviks** [comment]
This is likely fixed by #32. Please reopen if you are still having errors.
