### ISSUE TITLE
Update http://pkg.julialang.org version to current commit

### ISSUE THREAD

**Issue by kuitang** [johnmyleswhite/TextAnalysis.jl#30]
I am currently using the version on http://pkg.julialang.org which is at commit f022c37fbf1be8b5414a962ece186d6971e53b10.

There are several new features in the current (prepare and implementation of remove_words without regexes) commit that I, and certainly others, would like to use.

**Comment by johnmyleswhite** [comment]
If the newer version that you'd like to use passes tests, you could submit a pull request to METADATA to release the version you'd like to use.

**Comment by aviks** [comment]
Unfortunately, users without access to the underlying repository cannot do a Pkg.publish() to create a METADATA PR. I've created one the old fashioned way: https://github.com/JuliaLang/METADATA.jl/pull/2576

**Comment by aviks** [comment]
This is now fixed, and can be closed.
