### ISSUE TITLE
needs update for string.data changes

### ISSUE THREAD

**Issue by stevengj** [johnmyleswhite/TextAnalysis.jl#50]
After JuliaLang/julia#19449, soon to be merged for Julia 0.6, you will no longer be able to access the raw bytes of a string via `string.data`; instead, do `Vector{UInt8}(string)`.  For `length(string.data)`, just do `sizeof(string)`.  For example, this affects:

https://github.com/johnmyleswhite/TextAnalysis.jl/blob/4e6c7702726508a208dc150e6d1e21a4417741ff/src/preprocessing.jl#L303

**Comment by aviks** [comment]
Fixed by https://github.com/johnmyleswhite/TextAnalysis.jl/commit/5a77614ca4a50c98095f9032463534d0f78f724d
